db:
    image: postgres
    environment:
        - POSTGRES_DB=ApiManagerDS
        - POSTGRES_USER=apiman
        - POSTGRES_PASSWORD=apiman
        - POSTGRES_ROOT_PASSWORD=apiman

apiman:
    image: jboss/apiman-wildfly-admin
    environment:
        - KEYCLOAK_LOGLEVEL=DEBUG
    links:
        - db:postgres
    ports:
        - "8089:8080"
        - "9999:9990"
        - "443:8443"
        - "19200:19200"
        - "19300:19300"
        - "8787:8787"

